//*****************************************************************************
//*****************************************************************************
//  FILENAME: SELFTEST.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: SELFTEST User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SELFTEST_INCLUDE
#define SELFTEST_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  SELFTEST_Stop
#pragma fastcall16  SELFTEST_Start
#pragma fastcall16  SELFTEST_On
#pragma fastcall16  SELFTEST_Off
#pragma fastcall16  SELFTEST_Switch
#pragma fastcall16  SELFTEST_Invert
#pragma fastcall16  SELFTEST_GetState


//-------------------------------------------------
// Constants for SELFTEST API's.
//-------------------------------------------------
//
#define  SELFTEST_ON   1
#define  SELFTEST_OFF  0

//-------------------------------------------------
// Prototypes of the SELFTEST API.
//-------------------------------------------------
extern void  SELFTEST_Start(void);                                     
extern void  SELFTEST_Stop(void);                                      
extern void  SELFTEST_On(void);                                      
extern void  SELFTEST_Off(void);                                      
extern void  SELFTEST_Switch(BYTE bSwitch);
extern void  SELFTEST_Invert(void);                                         
extern BYTE  SELFTEST_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
