//*****************************************************************************
//*****************************************************************************
//  FILENAME: SELBSTTEst.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: SELBSTTEst User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SELBSTTEst_INCLUDE
#define SELBSTTEst_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  SELBSTTEst_Stop
#pragma fastcall16  SELBSTTEst_Start
#pragma fastcall16  SELBSTTEst_On
#pragma fastcall16  SELBSTTEst_Off
#pragma fastcall16  SELBSTTEst_Switch
#pragma fastcall16  SELBSTTEst_Invert
#pragma fastcall16  SELBSTTEst_GetState


//-------------------------------------------------
// Constants for SELBSTTEst API's.
//-------------------------------------------------
//
#define  SELBSTTEst_ON   1
#define  SELBSTTEst_OFF  0

//-------------------------------------------------
// Prototypes of the SELBSTTEst API.
//-------------------------------------------------
extern void  SELBSTTEst_Start(void);                                     
extern void  SELBSTTEst_Stop(void);                                      
extern void  SELBSTTEst_On(void);                                      
extern void  SELBSTTEst_Off(void);                                      
extern void  SELBSTTEst_Switch(BYTE bSwitch);
extern void  SELBSTTEst_Invert(void);                                         
extern BYTE  SELBSTTEst_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
