;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME:   SELBSTTEst.asm
;;  Version: 1.40, Updated on 2013/5/19 at 10:43:48
;;  Generated by PSoC Designer 5.4.2946
;;
;;  DESCRIPTION: LED user module.
;;
;;
;;  NOTE: User Module APIs conform to the fastcall16 convention for marshalling
;;        arguments and observe the associated "Registers are volatile" policy.
;;        This means it is the caller's responsibility to preserve any values
;;        in the X and A registers that are still needed after the API functions
;;        returns. For Large Memory Model devices it is also the caller's 
;;        responsibility to perserve any value in the CUR_PP, IDX_PP, MVR_PP and 
;;        MVW_PP registers. Even though some of these registers may not be modified
;;        now, there is no guarantee that will remain the case in future releases.
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "SELBSTTEst.inc"
include "memory.inc"

export _SELBSTTEst_Start
export  SELBSTTEst_Start

export _SELBSTTEst_Stop
export  SELBSTTEst_Stop

export _SELBSTTEst_On
export  SELBSTTEst_On

export _SELBSTTEst_Off
export  SELBSTTEst_Off

export _SELBSTTEst_Switch
export  SELBSTTEst_Switch

export _SELBSTTEst_Invert
export  SELBSTTEst_Invert

export _SELBSTTEst_GetState
export  SELBSTTEst_GetState


AREA UserModules (ROM, REL)


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: SELBSTTEst_Start(void)
;  FUNCTION NAME: SELBSTTEst_Stop(void)
;
;  FUNCTION NAME: SELBSTTEst_Switch(void)
;
;  DESCRIPTION: ( Switch )
;     Turn LED on or off     
;
;  DESCRIPTION: ( Start, Stop )
;     Turn LED off                       
;
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:  ( Switch )
;     A => If 0, turn off LED, if > 0 turn on LED
;
;  ARGUMENTS:  ( Start, Stop )
;      None
;
;  RETURNS:  none
;
;  SIDE EFFECTS:
;    REGISTERS ARE VOLATILE: THE A AND X REGISTERS MAY BE MODIFIED!
;
;-----------------------------------------------------------------------------
_SELBSTTEst_On:
 SELBSTTEst_On:
   mov  A,0x01
   jmp  SELBSTTEst_Switch 

_SELBSTTEst_Start:
 SELBSTTEst_Start:
_SELBSTTEst_Stop:
 SELBSTTEst_Stop:
_SELBSTTEst_Off:
 SELBSTTEst_Off:
   mov  A,0x00

_SELBSTTEst_Switch:
 SELBSTTEst_Switch:
   RAM_PROLOGUE RAM_USE_CLASS_4
   RAM_PROLOGUE RAM_USE_CLASS_2
   RAM_SETPAGE_CUR >NO_SHADOW

   or   A,0x00                                   ; Check mode
   jz   .Turn_Off_LED

.Turn_On_LED:
IF(0)                                            ; Active High Digit Drive
   or   [NO_SHADOW],SELBSTTEst_PinMask
ELSE                                             ; Active Low Digit Drive
   and  [NO_SHADOW],~SELBSTTEst_PinMask
ENDIF
   jmp  .Switch_LED

.Turn_Off_LED:
IF(0)                      ; Active High Digit Drive
   and  [NO_SHADOW],~SELBSTTEst_PinMask
ELSE                              ; Active Low Digit Drive
   or   [NO_SHADOW],SELBSTTEst_PinMask
ENDIF

.Switch_LED:
   mov  A,[NO_SHADOW]
   mov  reg[SELBSTTEst_PortDR],A

   RAM_EPILOGUE RAM_USE_CLASS_2
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION



.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: SELBSTTEst_Invert(void)
;
;  DESCRIPTION:
;     Invert state of LED                               
;
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: none
;
;  RETURNS:  none
;
;  SIDE EFFECTS:
;    REGISTERS ARE VOLATILE: THE A AND X REGISTERS MAY BE MODIFIED!
;
;-----------------------------------------------------------------------------
_SELBSTTEst_Invert:
 SELBSTTEst_Invert:
   RAM_PROLOGUE RAM_USE_CLASS_4
   RAM_PROLOGUE RAM_USE_CLASS_2
   RAM_SETPAGE_CUR >NO_SHADOW

   xor  [NO_SHADOW],SELBSTTEst_PinMask
   mov  A,[NO_SHADOW]
   mov  reg[SELBSTTEst_PortDR],A

   RAM_EPILOGUE RAM_USE_CLASS_2
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION

.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: SELBSTTEst_GetState(void)
;
;  DESCRIPTION:
;     Get state of LED
;
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: none
;
;  RETURNS:  
;    State of LED   1 = ON,  0 = OFF
;
;  SIDE EFFECTS:
;    REGISTERS ARE VOLATILE: THE A AND X REGISTERS MAY BE MODIFIED!
;
;-----------------------------------------------------------------------------
_SELBSTTEst_GetState:
 SELBSTTEst_GetState:
   RAM_PROLOGUE RAM_USE_CLASS_4
   RAM_PROLOGUE RAM_USE_CLASS_2
   RAM_SETPAGE_CUR >NO_SHADOW

   mov   A,[NO_SHADOW]                 ; Get shade value
IF(0)                                  ; Active High Digit Drive
   // Nothing for now
ELSE                                   ; Active Low Digit Drive
   cpl   A                             ; Invert bit if Active low
ENDIF
   and   A,SELBSTTEst_PinMask          ; Mask off the trash
   jz    .End_LED_GS                   ; If zero, we're done
   mov   A,0x01                        ; Return a 1 no mater what the mask is.

.End_LED_GS:
   RAM_EPILOGUE RAM_USE_CLASS_2
   RAM_EPILOGUE RAM_USE_CLASS_4
   ret
.ENDSECTION
