//*****************************************************************************
//*****************************************************************************
//  FILENAME: IN2.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: IN2 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef IN2_INCLUDE
#define IN2_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  IN2_Stop
#pragma fastcall16  IN2_Start
#pragma fastcall16  IN2_On
#pragma fastcall16  IN2_Off
#pragma fastcall16  IN2_Switch
#pragma fastcall16  IN2_Invert
#pragma fastcall16  IN2_GetState


//-------------------------------------------------
// Constants for IN2 API's.
//-------------------------------------------------
//
#define  IN2_ON   1
#define  IN2_OFF  0

//-------------------------------------------------
// Prototypes of the IN2 API.
//-------------------------------------------------
extern void  IN2_Start(void);                                     
extern void  IN2_Stop(void);                                      
extern void  IN2_On(void);                                      
extern void  IN2_Off(void);                                      
extern void  IN2_Switch(BYTE bSwitch);
extern void  IN2_Invert(void);                                         
extern BYTE  IN2_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
