//*****************************************************************************
//*****************************************************************************
//  FILENAME: SELBSTTEST.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: SELBSTTEST User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SELBSTTEST_INCLUDE
#define SELBSTTEST_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  SELBSTTEST_Stop
#pragma fastcall16  SELBSTTEST_Start
#pragma fastcall16  SELBSTTEST_On
#pragma fastcall16  SELBSTTEST_Off
#pragma fastcall16  SELBSTTEST_Switch
#pragma fastcall16  SELBSTTEST_Invert
#pragma fastcall16  SELBSTTEST_GetState


//-------------------------------------------------
// Constants for SELBSTTEST API's.
//-------------------------------------------------
//
#define  SELBSTTEST_ON   1
#define  SELBSTTEST_OFF  0

//-------------------------------------------------
// Prototypes of the SELBSTTEST API.
//-------------------------------------------------
extern void  SELBSTTEST_Start(void);                                     
extern void  SELBSTTEST_Stop(void);                                      
extern void  SELBSTTEST_On(void);                                      
extern void  SELBSTTEST_Off(void);                                      
extern void  SELBSTTEST_Switch(BYTE bSwitch);
extern void  SELBSTTEST_Invert(void);                                         
extern BYTE  SELBSTTEST_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
